// SPDX-License-Identifier: Apache-2.0
// @generated by tools/generate_sdk_models.py; do not edit.
export const CONTRACT_SHA256 = "abf4cb0e155877d22882ac3acbb6101f7e8f69c5a9ca25fce3ba846794724237" as const;

export type JsonInteger = number | bigint;

export type JsonValue =
  | null
  | boolean
  | JsonInteger
  | string
  | Array<JsonValue>
  | { [key: string]: JsonValue };

/** Optional grouped aggregation plan. */
export interface AggregationPlanV1 {
  /** Ordered group-key paths. */
  group_by: Array<Array<string>>;
  /** Named metrics. */
  metrics: Array<NamedMetricV1>;
}

/** Complete aggregation response. */
export interface AggregationResultV1 {
  /** Whether explicit group fields were requested. */
  grouped: boolean;
  /** Deterministically ordered groups. */
  groups: Array<GroupResultV1>;
}

/** Public server policy limits. */
export interface ApiLimitsV1 {
  /** Maximum distinct aggregation groups. */
  aggregation_groups: JsonInteger;
  /** Maximum records or keys in one atomic batch. */
  batch_items: JsonInteger;
  /** Maximum admitted concurrent data operations. */
  concurrent_operations: JsonInteger;
  /** Maximum canonical structured document payload bytes. */
  document_bytes: JsonInteger;
  /** Maximum recursive filter depth. */
  filter_depth: JsonInteger;
  /** Maximum recursive filter nodes. */
  filter_nodes: JsonInteger;
  /** Maximum aggregation group fields. */
  group_fields: JsonInteger;
  /** Maximum JSON nesting depth. */
  json_depth: JsonInteger;
  /** Maximum JSON nodes. */
  json_nodes: JsonInteger;
  /** Maximum decoded binary key bytes. */
  key_bytes: JsonInteger;
  /** Maximum matching lexical candidates retained before ranking. */
  lexical_candidates: JsonInteger;
  /** Maximum durable documents inspected by one lexical retrieval. */
  lexical_documents: JsonInteger;
  /** Maximum matches returned by lexical or hybrid retrieval. */
  lexical_results: JsonInteger;
  /** Maximum requested lexical retrieval timeout. */
  lexical_timeout_ms: JsonInteger;
  /** Maximum normalized tokens processed by one lexical retrieval. */
  lexical_tokens: JsonInteger;
  /** Maximum matched records retained by one query. */
  matched_records: JsonInteger;
  /** Maximum aggregation metrics. */
  metrics: JsonInteger;
  /** Maximum canonical result-proof bytes before base64 transport. */
  proof_bytes: JsonInteger;
  /** Maximum requested query timeout. */
  query_timeout_ms: JsonInteger;
  /** Maximum complete JSON request bytes. */
  request_body_bytes: JsonInteger;
  /** Maximum time allowed to receive one complete JSON body. */
  request_body_timeout_ms: JsonInteger;
  /** Maximum serialized JSON response bytes. */
  response_bytes: JsonInteger;
  /** Maximum rows returned by one query page. */
  result_rows: JsonInteger;
  /** Maximum aggregate candidate key and vector bytes loaded. */
  retrieval_candidate_bytes: JsonInteger;
  /** Maximum vectors inspected by one exact retrieval. */
  retrieval_candidates: JsonInteger;
  /** Maximum canonical retrieval-proof bytes before base64 transport. */
  retrieval_proof_bytes: JsonInteger;
  /** Maximum matches returned by one retrieval. */
  retrieval_results: JsonInteger;
  /** Maximum requested retrieval timeout. */
  retrieval_timeout_ms: JsonInteger;
  /** Maximum records inspected globally by one query. */
  scanned_records: JsonInteger;
  /** Maximum explicit sort fields. */
  sort_fields: JsonInteger;
  /** Maximum dimensions in one durable vector space. */
  vector_dimensions: JsonInteger;
  /** Maximum downloadable canonical snapshot witness bytes. */
  witness_bytes: JsonInteger;
}

/** Public capability response. */
export interface CapabilitiesV1 {
  /** Fixed API path version. */
  api_version: string;
  /** Current numeric data-directory format. */
  disk_format_version: JsonInteger;
  /** Sorted implemented feature identifiers. */
  features: Array<string>;
  /** Effective policy limits visible to clients. */
  limits: ApiLimitsV1;
}

/** Durable commit receipt. */
export interface CommitReceiptV1 {
  /** Commit-frame digest as hexadecimal. */
  commit_digest: string;
  /** Authoritative commit-frame sequence. */
  commit_sequence: JsonInteger;
  /** `committed` for a new commit or `existing` for an exact retry. */
  status: string;
  /** Canonical transaction digest as hexadecimal. */
  transaction_digest: string;
  /** UUID idempotency identifier. */
  transaction_id: string;
}

/** Ordered comparison operator. */
export type CompareOperatorV1 = "equal" | "not_equal" | "less" | "less_or_equal" | "greater" | "greater_or_equal";

/** Logical continuation cursor. */
export interface CursorV1 {
  /** Final binary key tie-breaker as hexadecimal. */
  key_hex: string;
  /** Normalized sort values; JSON null represents missing/null. */
  sort_values: Array<JsonValue>;
}

/** Atomic durable lexical-index definition request. */
export interface DefineLexicalIndexRequestV1 {
  /** Immutable lexical-index definition. */
  lexical_index: LexicalIndexV1;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector-space definition request. */
export interface DefineVectorSpaceRequestV1 {
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Immutable vector-space definition. */
  vector_space: VectorSpaceV1;
}

/** Atomic durable delete batch. */
export interface DeleteRequestV1 {
  /** Nonempty binary keys encoded as hexadecimal. */
  keys_hex: Array<string>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector deletion batch. */
export interface DeleteVectorsRequestV1 {
  /** Nonempty binary object keys encoded as hexadecimal. */
  keys_hex: Array<string>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Existing vector-space name. */
  vector_space: string;
}

/** Stable version 1 public error envelope. */
export interface ErrorV1 {
  /** Stable machine-readable error code. */
  code: string;
  /** Bounded human-readable diagnostic. */
  message: string;
  /** Generated request identifier also returned as a response header. */
  request_id: string;
}

/** Stable normal exact-retrieval abstention reason. */
export type ExactAbstentionReasonV1 = "no_candidates" | "below_threshold" | "ambiguous";

/** Stable exact-retrieval abstention evidence. */
export interface ExactAbstentionV1 {
  /** Best score when a candidate exists. */
  best_score_nanos?: JsonInteger | null;
  /** Stable reason. */
  reason: ExactAbstentionReasonV1;
  /** Runner-up score when one exists. */
  runner_up_score_nanos?: JsonInteger | null;
  /** Global candidates inspected. */
  scanned_candidates: JsonInteger;
}

/** One canonical exact-retrieval match. */
export interface ExactRetrievalMatchV1 {
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Canonical signed integer cosine score. */
  score_nanos: JsonInteger;
}

/** Complete durable exact-retrieval outcome. */
export type ExactRetrievalOutcomeV1 = {
  matches: Array<ExactRetrievalMatchV1>;
  scanned_candidates: JsonInteger;
  status: "matches";
} | {
  abstention: ExactAbstentionV1;
  status: "abstained";
};

/** Durable exact-retrieval request under reference semantics v2. */
export interface ExactRetrievalRequestV1 {
  /** Maximum returned matches. */
  limit: JsonInteger;
  /** Minimum canonical best/runner-up margin. */
  minimum_margin_nanos: JsonInteger;
  /** Inclusive minimum canonical cosine score. */
  minimum_score_nanos: JsonInteger;
  /** Canonical signed-Q15 query vector. */
  query: Array<JsonInteger>;
  /** Optional per-request timeout bounded by server policy. */
  timeout_ms?: JsonInteger | null;
  /** Existing vector-space name. */
  vector_space: string;
}

/** Proof-bearing durable exact-retrieval response. */
export interface ExactRetrievalResponseV1 {
  /** Complete matches or typed abstention. */
  outcome: ExactRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

/** Versioned recursive filter expression. */
export type FilterV1 = {
  op: "match_all";
} | {
  op: "exists";
  path: Array<string>;
} | {
  op: "compare";
  operator: CompareOperatorV1;
  path: Array<string>;
  value: JsonValue;
} | {
  op: "prefix";
  path: Array<string>;
  prefix: JsonValue;
} | {
  needle: JsonValue;
  op: "contains";
  path: Array<string>;
} | {
  filters: Array<FilterV1>;
  op: "all";
} | {
  filters: Array<FilterV1>;
  op: "any";
} | {
  filter: FilterV1;
  op: "not";
};

/** Exact durable KV lookup. */
export interface GetRequestV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
}

/** Proof-bearing exact lookup response. */
export interface GetResponseV1 {
  /** Whether the key exists at the proven checkpoint. */
  found: boolean;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Present record, or `null` for proven absence. */
  record?: RecordV1 | null;
}

/** One aggregation group-key component preserving missing versus explicit null. */
export type GroupKeyValueV1 = {
  kind: "missing";
} | {
  kind: "value";
  value: JsonValue;
};

/** One deterministic aggregate group. */
export interface GroupResultV1 {
  /** Ordered group values with an explicit missing/null distinction. */
  key: Array<GroupKeyValueV1>;
  /** Metric results in request order. */
  metrics: Array<NamedMetricResultV1>;
}

/** Liveness or readiness response. */
export interface HealthV1 {
  /** `live` or `ready`. */
  status: string;
}

/** Both hybrid branches abstained normally. */
export interface HybridAbstentionV1 {
  /** Lexical branch absence. */
  lexical: HybridBranchAbsenceV1;
  /** Exact-vector branch absence. */
  vector: HybridBranchAbsenceV1;
}

/** Preserved reason for one absent hybrid branch. */
export type HybridBranchAbsenceV1 = "lexical_no_candidates" | "vector_no_candidates" | "vector_below_threshold" | "vector_ambiguous";

/** Full deterministic explanation for one hybrid result. */
export interface HybridExplanationV1 {
  /** One-based final rank. */
  final_rank: JsonInteger;
  /** Checked contribution sum. */
  fusion_score: JsonInteger;
  /** Integer lexical RRF contribution. */
  lexical_contribution: JsonInteger;
  /** One-based lexical rank when present. */
  lexical_rank?: JsonInteger | null;
  /** Canonical lexical score when present. */
  lexical_score_nanos?: JsonInteger | null;
  /** Integer vector RRF contribution. */
  vector_contribution: JsonInteger;
  /** One-based exact-vector rank when present. */
  vector_rank?: JsonInteger | null;
  /** Canonical exact-vector score when present. */
  vector_score_nanos?: JsonInteger | null;
}

/** One canonical hybrid retrieval match. */
export interface HybridRetrievalMatchV1 {
  /** Complete fusion explanation. */
  explanation: HybridExplanationV1;
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
}

/** Complete deterministic hybrid retrieval outcome. */
export type HybridRetrievalOutcomeV1 = {
  lexical_absence?: HybridBranchAbsenceV1 | null;
  matches: Array<HybridRetrievalMatchV1>;
  status: "matches";
  vector_absence?: HybridBranchAbsenceV1 | null;
} | {
  abstention: HybridAbstentionV1;
  status: "abstained";
};

/** Complete hybrid retrieval request under deterministic RRF semantics v1. */
export interface HybridRetrievalRequestV1 {
  /** Complete lexical branch request and candidate limit. */
  lexical: LexicalRetrievalRequestV1;
  /** Positive lexical RRF weight in `1..=1_000_000`. */
  lexical_weight: JsonInteger;
  /** Maximum final matches after deduplication and fusion. */
  limit: JsonInteger;
  /** Complete exact-vector branch request and candidate limit. */
  vector: ExactRetrievalRequestV1;
  /** Positive vector RRF weight in `1..=1_000_000`. */
  vector_weight: JsonInteger;
}

/** Proof-bearing deterministic hybrid retrieval response. */
export interface HybridRetrievalResponseV1 {
  /** Complete fused matches or typed abstention. */
  outcome: HybridRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

/** Stable normal lexical abstention reason. */
export type LexicalAbstentionReasonV1 = "no_candidates";

/** Stable lexical abstention evidence. */
export interface LexicalAbstentionV1 {
  /** Canonical unique normalized query tokens. */
  query_tokens: Array<string>;
  /** Stable reason. */
  reason: LexicalAbstentionReasonV1;
  /** Durable documents inspected. */
  scanned_documents: JsonInteger;
}

/** One configured-field contribution to a lexical term score. */
export interface LexicalFieldContributionV1 {
  /** Normalized field token length. */
  field_length: JsonInteger;
  /** Canonical exact field path. */
  path: Array<string>;
  /** Raw term frequency in this field. */
  term_frequency: JsonInteger;
}

/** One configured field in an immutable lexical-index definition. */
export interface LexicalFieldV1 {
  /** Nonempty exact object path. */
  path: Array<string>;
  /** Positive field weight in millionths. */
  weight_micros: JsonInteger;
}

/** One immutable provider-free lexical-index definition. */
export interface LexicalIndexV1 {
  /** Nonempty unique fields; the server canonicalizes path order. */
  fields: Array<LexicalFieldV1>;
  /** Stable lowercase index name. */
  name: string;
}

/** One canonical lexical retrieval match. */
export interface LexicalRetrievalMatchV1 {
  /** Binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Canonical BM25F score in nanos. */
  score_nanos: JsonInteger;
  /** Deterministic per-term explanation. */
  terms: Array<LexicalTermContributionV1>;
}

/** Complete durable lexical retrieval outcome. */
export type LexicalRetrievalOutcomeV1 = {
  matched_documents: JsonInteger;
  matches: Array<LexicalRetrievalMatchV1>;
  query_tokens: Array<string>;
  scanned_documents: JsonInteger;
  status: "matches";
} | {
  abstention: LexicalAbstentionV1;
  status: "abstained";
};

/** Durable provider-free lexical retrieval request under semantics v1. */
export interface LexicalRetrievalRequestV1 {
  /** Existing lexical-index name. */
  lexical_index: string;
  /** Maximum returned matches. */
  limit: JsonInteger;
  /** UTF-8 query analyzed by tokenizer v1. */
  query: string;
  /** Optional per-request timeout bounded by server policy. */
  timeout_ms?: JsonInteger | null;
}

/** Proof-bearing durable lexical retrieval response. */
export interface LexicalRetrievalResponseV1 {
  /** Complete matches or typed abstention. */
  outcome: LexicalRetrievalOutcomeV1;
  /** Canonical retrieval proof and witness identity. */
  proof: RetrievalProofV1;
}

/** One canonical query-term contribution to a lexical result. */
export interface LexicalTermContributionV1 {
  /** Corpus document frequency. */
  document_frequency: JsonInteger;
  /** Configured fields in canonical path order. */
  fields: Array<LexicalFieldContributionV1>;
  /** Quantized BM25F contribution. */
  score_nanos: JsonInteger;
  /** Canonical tokenizer-v1 token. */
  token: string;
}

/** Versioned aggregate metric output. */
export type MetricValueV1 = {
  kind: "count";
  value: JsonInteger;
} | {
  kind: "integer";
  value?: string | null;
} | {
  kind: "value";
  value?: JsonValue;
};

/** Named aggregate result. */
export interface NamedMetricResultV1 {
  /** Metric name from the request. */
  name: string;
  /** Typed metric value. */
  result: MetricValueV1;
}

/** One named aggregation metric. */
export type NamedMetricV1 = {
  metric: "count";
  name: string;
} | {
  metric: "sum";
  name: string;
  path: Array<string>;
} | {
  metric: "min";
  name: string;
  path: Array<string>;
} | {
  metric: "max";
  name: string;
  path: Array<string>;
};

/** Wire null placement. */
export type NullPlacementV1 = "first" | "last";

/** Portable result proof plus its downloadable witness reference. */
export interface ProofV1 {
  /** Caller-pinnable anchor digest as hexadecimal. */
  anchor_digest: string;
  /** Commit digest as hexadecimal, absent for empty history. */
  checkpoint_digest?: string | null;
  /** Snapshot/log checkpoint sequence. */
  checkpoint_sequence: JsonInteger;
  /** Canonical `.hyproof` bytes in standard padded base64. */
  data: string;
  /** Fixed encoding identifier `base64`. */
  encoding: string;
  /** Canonical proof digest as hexadecimal. */
  proof_digest: string;
  /** Canonical logical snapshot digest as hexadecimal. */
  snapshot_digest: string;
  /** Authenticated endpoint for the complete offline witness. */
  witness: WitnessV1;
}

/** Atomic durable put batch. */
export interface PutRequestV1 {
  /** Nonempty atomic record batch. */
  records: Array<RecordV1>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Atomic durable vector upsert batch. */
export interface PutVectorsRequestV1 {
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
  /** Existing vector-space name. */
  vector_space: string;
  /** Nonempty atomic vector batch. */
  vectors: Array<VectorV1>;
}

/** Complete version 1 structured query request. */
export interface QueryRequestV1 {
  /** Optional global or grouped aggregation. */
  aggregation?: AggregationPlanV1 | null;
  /** Optional logical continuation cursor. */
  cursor?: CursorV1 | null;
  /** Recursive filter; defaults to match-all. */
  filter?: FilterV1;
  /** Final page size. */
  limit: JsonInteger;
  /** Deterministic sort fields. */
  sort?: Array<SortFieldV1>;
  /** Requested cooperative query timeout. */
  timeout_ms?: JsonInteger | null;
}

/** Proof-bearing structured query response. */
export interface QueryResponseV1 {
  /** Optional complete aggregation. */
  aggregation?: AggregationResultV1 | null;
  /** Records matching before pagination. */
  matched_records: JsonInteger;
  /** Logical continuation cursor when more rows exist. */
  next_cursor?: CursorV1 | null;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Final page rows. */
  rows: Array<RecordV1>;
  /** Records inspected globally. */
  scanned_records: JsonInteger;
}

/** One structured record on the wire. */
export interface RecordV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
  /** Natural JSON structured value with the reserved bytes envelope. */
  value: JsonValue;
}

/** Portable retrieval proof plus its downloadable witness reference. */
export interface RetrievalProofV1 {
  /** Caller-pinnable retrieval anchor digest as hexadecimal. */
  anchor_digest: string;
  /** Commit digest as hexadecimal, absent for empty history. */
  checkpoint_digest?: string | null;
  /** Snapshot/log checkpoint sequence. */
  checkpoint_sequence: JsonInteger;
  /** Canonical `.hyrproof` bytes in standard padded base64. */
  data: string;
  /** Fixed encoding identifier `base64`. */
  encoding: string;
  /** Canonical proof digest as hexadecimal. */
  proof_digest: string;
  /** Canonical logical snapshot digest as hexadecimal. */
  snapshot_digest: string;
  /** Authenticated endpoint for the complete offline witness. */
  witness: WitnessV1;
}

/** Wire sort direction. */
export type SortDirectionV1 = "ascending" | "descending";

/** One versioned sort field. */
export interface SortFieldV1 {
  /** Value direction. */
  direction: SortDirectionV1;
  /** Explicit missing/null placement. */
  nulls: NullPlacementV1;
  /** Exact object path. */
  path: Array<string>;
}

/** Canonical durable vector metric. */
export type VectorMetricV1 = "cosine_q15_nanos";

/** One immutable durable vector-space definition. */
export interface VectorSpaceV1 {
  /** Fixed number of signed-Q15 elements. */
  dimension: JsonInteger;
  /** Canonical scoring metric. */
  metric: VectorMetricV1;
  /** Stable lowercase vector-space name. */
  name: string;
}

/** One canonical signed-Q15 vector on the wire. */
export interface VectorV1 {
  /** Nonempty binary object key encoded as hexadecimal. */
  key_hex: string;
  /** Signed-Q15 elements whose length must match the space dimension. */
  values: Array<JsonInteger>;
}

/** Download reference for one canonical logical snapshot. */
export interface WitnessV1 {
  /** Complete snapshot file length. */
  file_bytes: JsonInteger;
  /** Versioned relative HTTP path. */
  path: string;
}
