// SPDX-License-Identifier: Apache-2.0
// @generated by tools/generate_sdk_models.py; do not edit.
export const CONTRACT_SHA256 = "830a8b2d4b4425359677c3ce3899d72d98afa73094c805948112178fe62d4970" as const;

export type JsonInteger = number | bigint;

export type JsonValue =
  | null
  | boolean
  | JsonInteger
  | string
  | Array<JsonValue>
  | { [key: string]: JsonValue };

/** Optional grouped aggregation plan. */
export interface AggregationPlanV1 {
  /** Ordered group-key paths. */
  group_by: Array<Array<string>>;
  /** Named metrics. */
  metrics: Array<NamedMetricV1>;
}

/** Complete aggregation response. */
export interface AggregationResultV1 {
  /** Whether explicit group fields were requested. */
  grouped: boolean;
  /** Deterministically ordered groups. */
  groups: Array<GroupResultV1>;
}

/** Public server policy limits. */
export interface ApiLimitsV1 {
  /** Maximum distinct aggregation groups. */
  aggregation_groups: JsonInteger;
  /** Maximum records or keys in one atomic batch. */
  batch_items: JsonInteger;
  /** Maximum admitted concurrent data operations. */
  concurrent_operations: JsonInteger;
  /** Maximum canonical structured document payload bytes. */
  document_bytes: JsonInteger;
  /** Maximum recursive filter depth. */
  filter_depth: JsonInteger;
  /** Maximum recursive filter nodes. */
  filter_nodes: JsonInteger;
  /** Maximum aggregation group fields. */
  group_fields: JsonInteger;
  /** Maximum JSON nesting depth. */
  json_depth: JsonInteger;
  /** Maximum JSON nodes. */
  json_nodes: JsonInteger;
  /** Maximum decoded binary key bytes. */
  key_bytes: JsonInteger;
  /** Maximum matched records retained by one query. */
  matched_records: JsonInteger;
  /** Maximum aggregation metrics. */
  metrics: JsonInteger;
  /** Maximum canonical result-proof bytes before base64 transport. */
  proof_bytes: JsonInteger;
  /** Maximum requested query timeout. */
  query_timeout_ms: JsonInteger;
  /** Maximum complete JSON request bytes. */
  request_body_bytes: JsonInteger;
  /** Maximum time allowed to receive one complete JSON body. */
  request_body_timeout_ms: JsonInteger;
  /** Maximum serialized JSON response bytes. */
  response_bytes: JsonInteger;
  /** Maximum rows returned by one query page. */
  result_rows: JsonInteger;
  /** Maximum records inspected globally by one query. */
  scanned_records: JsonInteger;
  /** Maximum explicit sort fields. */
  sort_fields: JsonInteger;
  /** Maximum downloadable canonical snapshot witness bytes. */
  witness_bytes: JsonInteger;
}

/** Public capability response. */
export interface CapabilitiesV1 {
  /** Fixed API path version. */
  api_version: string;
  /** Current numeric data-directory format. */
  disk_format_version: JsonInteger;
  /** Sorted implemented feature identifiers. */
  features: Array<string>;
  /** Effective policy limits visible to clients. */
  limits: ApiLimitsV1;
}

/** Durable commit receipt. */
export interface CommitReceiptV1 {
  /** Commit-frame digest as hexadecimal. */
  commit_digest: string;
  /** Authoritative commit-frame sequence. */
  commit_sequence: JsonInteger;
  /** `committed` for a new commit or `existing` for an exact retry. */
  status: string;
  /** Canonical transaction digest as hexadecimal. */
  transaction_digest: string;
  /** UUID idempotency identifier. */
  transaction_id: string;
}

/** Ordered comparison operator. */
export type CompareOperatorV1 = "equal" | "not_equal" | "less" | "less_or_equal" | "greater" | "greater_or_equal";

/** Logical continuation cursor. */
export interface CursorV1 {
  /** Final binary key tie-breaker as hexadecimal. */
  key_hex: string;
  /** Normalized sort values; JSON null represents missing/null. */
  sort_values: Array<JsonValue>;
}

/** Atomic durable delete batch. */
export interface DeleteRequestV1 {
  /** Nonempty binary keys encoded as hexadecimal. */
  keys_hex: Array<string>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Stable version 1 public error envelope. */
export interface ErrorV1 {
  /** Stable machine-readable error code. */
  code: string;
  /** Bounded human-readable diagnostic. */
  message: string;
  /** Generated request identifier also returned as a response header. */
  request_id: string;
}

/** Versioned recursive filter expression. */
export type FilterV1 = {
  op: "match_all";
} | {
  op: "exists";
  path: Array<string>;
} | {
  op: "compare";
  operator: CompareOperatorV1;
  path: Array<string>;
  value: JsonValue;
} | {
  op: "prefix";
  path: Array<string>;
  prefix: JsonValue;
} | {
  needle: JsonValue;
  op: "contains";
  path: Array<string>;
} | {
  filters: Array<FilterV1>;
  op: "all";
} | {
  filters: Array<FilterV1>;
  op: "any";
} | {
  filter: FilterV1;
  op: "not";
};

/** Exact durable KV lookup. */
export interface GetRequestV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
}

/** Proof-bearing exact lookup response. */
export interface GetResponseV1 {
  /** Whether the key exists at the proven checkpoint. */
  found: boolean;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Present record, or `null` for proven absence. */
  record?: RecordV1 | null;
}

/** One aggregation group-key component preserving missing versus explicit null. */
export type GroupKeyValueV1 = {
  kind: "missing";
} | {
  kind: "value";
  value: JsonValue;
};

/** One deterministic aggregate group. */
export interface GroupResultV1 {
  /** Ordered group values with an explicit missing/null distinction. */
  key: Array<GroupKeyValueV1>;
  /** Metric results in request order. */
  metrics: Array<NamedMetricResultV1>;
}

/** Liveness or readiness response. */
export interface HealthV1 {
  /** `live` or `ready`. */
  status: string;
}

/** Versioned aggregate metric output. */
export type MetricValueV1 = {
  kind: "count";
  value: JsonInteger;
} | {
  kind: "integer";
  value?: string | null;
} | {
  kind: "value";
  value?: JsonValue;
};

/** Named aggregate result. */
export interface NamedMetricResultV1 {
  /** Metric name from the request. */
  name: string;
  /** Typed metric value. */
  result: MetricValueV1;
}

/** One named aggregation metric. */
export type NamedMetricV1 = {
  metric: "count";
  name: string;
} | {
  metric: "sum";
  name: string;
  path: Array<string>;
} | {
  metric: "min";
  name: string;
  path: Array<string>;
} | {
  metric: "max";
  name: string;
  path: Array<string>;
};

/** Wire null placement. */
export type NullPlacementV1 = "first" | "last";

/** Portable result proof plus its downloadable witness reference. */
export interface ProofV1 {
  /** Caller-pinnable anchor digest as hexadecimal. */
  anchor_digest: string;
  /** Commit digest as hexadecimal, absent for empty history. */
  checkpoint_digest?: string | null;
  /** Snapshot/log checkpoint sequence. */
  checkpoint_sequence: JsonInteger;
  /** Canonical `.hyproof` bytes in standard padded base64. */
  data: string;
  /** Fixed encoding identifier `base64`. */
  encoding: string;
  /** Canonical proof digest as hexadecimal. */
  proof_digest: string;
  /** Canonical logical snapshot digest as hexadecimal. */
  snapshot_digest: string;
  /** Authenticated endpoint for the complete offline witness. */
  witness: WitnessV1;
}

/** Atomic durable put batch. */
export interface PutRequestV1 {
  /** Nonempty atomic record batch. */
  records: Array<RecordV1>;
  /** Optional UUID idempotency key; a `UUIDv7` is generated when absent. */
  transaction_id?: string | null;
}

/** Complete version 1 structured query request. */
export interface QueryRequestV1 {
  /** Optional global or grouped aggregation. */
  aggregation?: AggregationPlanV1 | null;
  /** Optional logical continuation cursor. */
  cursor?: CursorV1 | null;
  /** Recursive filter; defaults to match-all. */
  filter?: FilterV1;
  /** Final page size. */
  limit: JsonInteger;
  /** Deterministic sort fields. */
  sort?: Array<SortFieldV1>;
  /** Requested cooperative query timeout. */
  timeout_ms?: JsonInteger | null;
}

/** Proof-bearing structured query response. */
export interface QueryResponseV1 {
  /** Optional complete aggregation. */
  aggregation?: AggregationResultV1 | null;
  /** Records matching before pagination. */
  matched_records: JsonInteger;
  /** Logical continuation cursor when more rows exist. */
  next_cursor?: CursorV1 | null;
  /** Complete result proof and witness identity. */
  proof: ProofV1;
  /** Final page rows. */
  rows: Array<RecordV1>;
  /** Records inspected globally. */
  scanned_records: JsonInteger;
}

/** One structured record on the wire. */
export interface RecordV1 {
  /** Nonempty binary key encoded as hexadecimal. */
  key_hex: string;
  /** Natural JSON structured value with the reserved bytes envelope. */
  value: JsonValue;
}

/** Wire sort direction. */
export type SortDirectionV1 = "ascending" | "descending";

/** One versioned sort field. */
export interface SortFieldV1 {
  /** Value direction. */
  direction: SortDirectionV1;
  /** Explicit missing/null placement. */
  nulls: NullPlacementV1;
  /** Exact object path. */
  path: Array<string>;
}

/** Download reference for one canonical logical snapshot. */
export interface WitnessV1 {
  /** Complete snapshot file length. */
  file_bytes: JsonInteger;
  /** Versioned relative HTTP path. */
  path: string;
}
