# SPDX-License-Identifier: Apache-2.0
# @generated by tools/generate_sdk_models.py; do not edit.
from __future__ import annotations

from typing import Literal, Never, NotRequired, TypeAlias, TypedDict

CONTRACT_SHA256 = "830a8b2d4b4425359677c3ce3899d72d98afa73094c805948112178fe62d4970"

JsonValue: TypeAlias = (
    None | bool | int | str | list["JsonValue"] | dict[str, "JsonValue"]
)

class AggregationPlanV1(TypedDict):
    """Optional grouped aggregation plan."""
    group_by: list[list[str]]
    metrics: list[NamedMetricV1]

class AggregationResultV1(TypedDict):
    """Complete aggregation response."""
    grouped: bool
    groups: list[GroupResultV1]

class ApiLimitsV1(TypedDict):
    """Public server policy limits."""
    aggregation_groups: int
    batch_items: int
    concurrent_operations: int
    document_bytes: int
    filter_depth: int
    filter_nodes: int
    group_fields: int
    json_depth: int
    json_nodes: int
    key_bytes: int
    matched_records: int
    metrics: int
    proof_bytes: int
    query_timeout_ms: int
    request_body_bytes: int
    request_body_timeout_ms: int
    response_bytes: int
    result_rows: int
    scanned_records: int
    sort_fields: int
    witness_bytes: int

class CapabilitiesV1(TypedDict):
    """Public capability response."""
    api_version: str
    disk_format_version: int
    features: list[str]
    limits: ApiLimitsV1

class CommitReceiptV1(TypedDict):
    """Durable commit receipt."""
    commit_digest: str
    commit_sequence: int
    status: str
    transaction_digest: str
    transaction_id: str

class CursorV1(TypedDict):
    """Logical continuation cursor."""
    key_hex: str
    sort_values: list[JsonValue]

class DeleteRequestV1(TypedDict):
    """Atomic durable delete batch."""
    keys_hex: list[str]
    transaction_id: NotRequired[str | None]

class ErrorV1(TypedDict):
    """Stable version 1 public error envelope."""
    code: str
    message: str
    request_id: str

class FilterV1MatchAll(TypedDict):
    """Match every record."""
    op: Literal["match_all"]

class FilterV1Exists(TypedDict):
    """Test whether a path resolves."""
    op: Literal["exists"]
    path: list[str]

class FilterV1Compare(TypedDict):
    """Compare one resolved value."""
    op: Literal["compare"]
    operator: CompareOperatorV1
    path: list[str]
    value: JsonValue

class FilterV1Prefix(TypedDict):
    """Test a string or bytes prefix."""
    op: Literal["prefix"]
    path: list[str]
    prefix: JsonValue

class FilterV1Contains(TypedDict):
    """Test array membership, string substring, or byte subsequence."""
    needle: JsonValue
    op: Literal["contains"]
    path: list[str]

class FilterV1All(TypedDict):
    """Require every child."""
    filters: list[FilterV1]
    op: Literal["all"]

class FilterV1Any(TypedDict):
    """Require at least one child."""
    filters: list[FilterV1]
    op: Literal["any"]

class FilterV1Not(TypedDict):
    """Negate one child."""
    filter: FilterV1
    op: Literal["not"]

class GetRequestV1(TypedDict):
    """Exact durable KV lookup."""
    key_hex: str

class GetResponseV1(TypedDict):
    """Proof-bearing exact lookup response."""
    found: bool
    proof: ProofV1
    record: NotRequired[RecordV1 | None]

class GroupKeyValueV1Missing(TypedDict):
    """The requested field path did not resolve."""
    kind: Literal["missing"]

class GroupKeyValueV1Value(TypedDict):
    """The path resolved, including when the structured value is explicit null."""
    kind: Literal["value"]
    value: JsonValue

class GroupResultV1(TypedDict):
    """One deterministic aggregate group."""
    key: list[GroupKeyValueV1]
    metrics: list[NamedMetricResultV1]

class HealthV1(TypedDict):
    """Liveness or readiness response."""
    status: str

class MetricValueV1Count(TypedDict):
    """Unsigned count."""
    kind: Literal["count"]
    value: int

class MetricValueV1Integer(TypedDict):
    """Checked signed integer, represented as decimal to preserve `i128`."""
    kind: Literal["integer"]
    value: NotRequired[str | None]

class MetricValueV1Value(TypedDict):
    """Minimum or maximum structured value."""
    kind: Literal["value"]
    value: NotRequired[JsonValue]

class NamedMetricResultV1(TypedDict):
    """Named aggregate result."""
    name: str
    result: MetricValueV1

class NamedMetricV1Count(TypedDict):
    """Count every matched record."""
    metric: Literal["count"]
    name: str

class NamedMetricV1Sum(TypedDict):
    """Checked integer sum."""
    metric: Literal["sum"]
    name: str
    path: list[str]

class NamedMetricV1Min(TypedDict):
    """Minimum non-null value."""
    metric: Literal["min"]
    name: str
    path: list[str]

class NamedMetricV1Max(TypedDict):
    """Maximum non-null value."""
    metric: Literal["max"]
    name: str
    path: list[str]

class ProofV1(TypedDict):
    """Portable result proof plus its downloadable witness reference."""
    anchor_digest: str
    checkpoint_digest: NotRequired[str | None]
    checkpoint_sequence: int
    data: str
    encoding: str
    proof_digest: str
    snapshot_digest: str
    witness: WitnessV1

class PutRequestV1(TypedDict):
    """Atomic durable put batch."""
    records: list[RecordV1]
    transaction_id: NotRequired[str | None]

class QueryRequestV1(TypedDict):
    """Complete version 1 structured query request."""
    aggregation: NotRequired[AggregationPlanV1 | None]
    cursor: NotRequired[CursorV1 | None]
    filter: NotRequired[FilterV1]
    limit: int
    sort: NotRequired[list[SortFieldV1]]
    timeout_ms: NotRequired[int | None]

class QueryResponseV1(TypedDict):
    """Proof-bearing structured query response."""
    aggregation: NotRequired[AggregationResultV1 | None]
    matched_records: int
    next_cursor: NotRequired[CursorV1 | None]
    proof: ProofV1
    rows: list[RecordV1]
    scanned_records: int

class RecordV1(TypedDict):
    """One structured record on the wire."""
    key_hex: str
    value: JsonValue

class SortFieldV1(TypedDict):
    """One versioned sort field."""
    direction: SortDirectionV1
    nulls: NullPlacementV1
    path: list[str]

class WitnessV1(TypedDict):
    """Download reference for one canonical logical snapshot."""
    file_bytes: int
    path: str

CompareOperatorV1: TypeAlias = Literal["equal"] | Literal["not_equal"] | Literal["less"] | Literal["less_or_equal"] | Literal["greater"] | Literal["greater_or_equal"]
FilterV1: TypeAlias = FilterV1MatchAll | FilterV1Exists | FilterV1Compare | FilterV1Prefix | FilterV1Contains | FilterV1All | FilterV1Any | FilterV1Not
GroupKeyValueV1: TypeAlias = GroupKeyValueV1Missing | GroupKeyValueV1Value
MetricValueV1: TypeAlias = MetricValueV1Count | MetricValueV1Integer | MetricValueV1Value
NamedMetricV1: TypeAlias = NamedMetricV1Count | NamedMetricV1Sum | NamedMetricV1Min | NamedMetricV1Max
NullPlacementV1: TypeAlias = Literal["first"] | Literal["last"]
SortDirectionV1: TypeAlias = Literal["ascending"] | Literal["descending"]

__all__ = [
    "AggregationPlanV1",
    "AggregationResultV1",
    "ApiLimitsV1",
    "CONTRACT_SHA256",
    "CapabilitiesV1",
    "CommitReceiptV1",
    "CompareOperatorV1",
    "CursorV1",
    "DeleteRequestV1",
    "ErrorV1",
    "FilterV1",
    "FilterV1All",
    "FilterV1Any",
    "FilterV1Compare",
    "FilterV1Contains",
    "FilterV1Exists",
    "FilterV1MatchAll",
    "FilterV1Not",
    "FilterV1Prefix",
    "GetRequestV1",
    "GetResponseV1",
    "GroupKeyValueV1",
    "GroupKeyValueV1Missing",
    "GroupKeyValueV1Value",
    "GroupResultV1",
    "HealthV1",
    "JsonValue",
    "MetricValueV1",
    "MetricValueV1Count",
    "MetricValueV1Integer",
    "MetricValueV1Value",
    "NamedMetricResultV1",
    "NamedMetricV1",
    "NamedMetricV1Count",
    "NamedMetricV1Max",
    "NamedMetricV1Min",
    "NamedMetricV1Sum",
    "NullPlacementV1",
    "ProofV1",
    "PutRequestV1",
    "QueryRequestV1",
    "QueryResponseV1",
    "RecordV1",
    "SortDirectionV1",
    "SortFieldV1",
    "WitnessV1",
]
