# SPDX-License-Identifier: Apache-2.0
# @generated by tools/generate_sdk_models.py; do not edit.
from __future__ import annotations

from typing import Literal, Never, NotRequired, TypeAlias, TypedDict

CONTRACT_SHA256 = "abf4cb0e155877d22882ac3acbb6101f7e8f69c5a9ca25fce3ba846794724237"

JsonValue: TypeAlias = (
    None | bool | int | str | list["JsonValue"] | dict[str, "JsonValue"]
)

class AggregationPlanV1(TypedDict):
    """Optional grouped aggregation plan."""
    group_by: list[list[str]]
    metrics: list[NamedMetricV1]

class AggregationResultV1(TypedDict):
    """Complete aggregation response."""
    grouped: bool
    groups: list[GroupResultV1]

class ApiLimitsV1(TypedDict):
    """Public server policy limits."""
    aggregation_groups: int
    batch_items: int
    concurrent_operations: int
    document_bytes: int
    filter_depth: int
    filter_nodes: int
    group_fields: int
    json_depth: int
    json_nodes: int
    key_bytes: int
    lexical_candidates: int
    lexical_documents: int
    lexical_results: int
    lexical_timeout_ms: int
    lexical_tokens: int
    matched_records: int
    metrics: int
    proof_bytes: int
    query_timeout_ms: int
    request_body_bytes: int
    request_body_timeout_ms: int
    response_bytes: int
    result_rows: int
    retrieval_candidate_bytes: int
    retrieval_candidates: int
    retrieval_proof_bytes: int
    retrieval_results: int
    retrieval_timeout_ms: int
    scanned_records: int
    sort_fields: int
    vector_dimensions: int
    witness_bytes: int

class CapabilitiesV1(TypedDict):
    """Public capability response."""
    api_version: str
    disk_format_version: int
    features: list[str]
    limits: ApiLimitsV1

class CommitReceiptV1(TypedDict):
    """Durable commit receipt."""
    commit_digest: str
    commit_sequence: int
    status: str
    transaction_digest: str
    transaction_id: str

class CursorV1(TypedDict):
    """Logical continuation cursor."""
    key_hex: str
    sort_values: list[JsonValue]

class DefineLexicalIndexRequestV1(TypedDict):
    """Atomic durable lexical-index definition request."""
    lexical_index: LexicalIndexV1
    transaction_id: NotRequired[str | None]

class DefineVectorSpaceRequestV1(TypedDict):
    """Atomic durable vector-space definition request."""
    transaction_id: NotRequired[str | None]
    vector_space: VectorSpaceV1

class DeleteRequestV1(TypedDict):
    """Atomic durable delete batch."""
    keys_hex: list[str]
    transaction_id: NotRequired[str | None]

class DeleteVectorsRequestV1(TypedDict):
    """Atomic durable vector deletion batch."""
    keys_hex: list[str]
    transaction_id: NotRequired[str | None]
    vector_space: str

class ErrorV1(TypedDict):
    """Stable version 1 public error envelope."""
    code: str
    message: str
    request_id: str

class ExactAbstentionV1(TypedDict):
    """Stable exact-retrieval abstention evidence."""
    best_score_nanos: NotRequired[int | None]
    reason: ExactAbstentionReasonV1
    runner_up_score_nanos: NotRequired[int | None]
    scanned_candidates: int

class ExactRetrievalMatchV1(TypedDict):
    """One canonical exact-retrieval match."""
    key_hex: str
    score_nanos: int

class ExactRetrievalOutcomeV1Matches(TypedDict):
    """Accepted globally ranked matches."""
    matches: list[ExactRetrievalMatchV1]
    scanned_candidates: int
    status: Literal["matches"]

class ExactRetrievalOutcomeV1Abstained(TypedDict):
    """Typed normal abstention."""
    abstention: ExactAbstentionV1
    status: Literal["abstained"]

class ExactRetrievalRequestV1(TypedDict):
    """Durable exact-retrieval request under reference semantics v2."""
    limit: int
    minimum_margin_nanos: int
    minimum_score_nanos: int
    query: list[int]
    timeout_ms: NotRequired[int | None]
    vector_space: str

class ExactRetrievalResponseV1(TypedDict):
    """Proof-bearing durable exact-retrieval response."""
    outcome: ExactRetrievalOutcomeV1
    proof: RetrievalProofV1

class FilterV1MatchAll(TypedDict):
    """Match every record."""
    op: Literal["match_all"]

class FilterV1Exists(TypedDict):
    """Test whether a path resolves."""
    op: Literal["exists"]
    path: list[str]

class FilterV1Compare(TypedDict):
    """Compare one resolved value."""
    op: Literal["compare"]
    operator: CompareOperatorV1
    path: list[str]
    value: JsonValue

class FilterV1Prefix(TypedDict):
    """Test a string or bytes prefix."""
    op: Literal["prefix"]
    path: list[str]
    prefix: JsonValue

class FilterV1Contains(TypedDict):
    """Test array membership, string substring, or byte subsequence."""
    needle: JsonValue
    op: Literal["contains"]
    path: list[str]

class FilterV1All(TypedDict):
    """Require every child."""
    filters: list[FilterV1]
    op: Literal["all"]

class FilterV1Any(TypedDict):
    """Require at least one child."""
    filters: list[FilterV1]
    op: Literal["any"]

class FilterV1Not(TypedDict):
    """Negate one child."""
    filter: FilterV1
    op: Literal["not"]

class GetRequestV1(TypedDict):
    """Exact durable KV lookup."""
    key_hex: str

class GetResponseV1(TypedDict):
    """Proof-bearing exact lookup response."""
    found: bool
    proof: ProofV1
    record: NotRequired[RecordV1 | None]

class GroupKeyValueV1Missing(TypedDict):
    """The requested field path did not resolve."""
    kind: Literal["missing"]

class GroupKeyValueV1Value(TypedDict):
    """The path resolved, including when the structured value is explicit null."""
    kind: Literal["value"]
    value: JsonValue

class GroupResultV1(TypedDict):
    """One deterministic aggregate group."""
    key: list[GroupKeyValueV1]
    metrics: list[NamedMetricResultV1]

class HealthV1(TypedDict):
    """Liveness or readiness response."""
    status: str

class HybridAbstentionV1(TypedDict):
    """Both hybrid branches abstained normally."""
    lexical: HybridBranchAbsenceV1
    vector: HybridBranchAbsenceV1

class HybridExplanationV1(TypedDict):
    """Full deterministic explanation for one hybrid result."""
    final_rank: int
    fusion_score: int
    lexical_contribution: int
    lexical_rank: NotRequired[int | None]
    lexical_score_nanos: NotRequired[int | None]
    vector_contribution: int
    vector_rank: NotRequired[int | None]
    vector_score_nanos: NotRequired[int | None]

class HybridRetrievalMatchV1(TypedDict):
    """One canonical hybrid retrieval match."""
    explanation: HybridExplanationV1
    key_hex: str

class HybridRetrievalOutcomeV1Matches(TypedDict):
    """Fused or explicit single-modality matches."""
    lexical_absence: NotRequired[HybridBranchAbsenceV1 | None]
    matches: list[HybridRetrievalMatchV1]
    status: Literal["matches"]
    vector_absence: NotRequired[HybridBranchAbsenceV1 | None]

class HybridRetrievalOutcomeV1Abstained(TypedDict):
    """Both branches abstained."""
    abstention: HybridAbstentionV1
    status: Literal["abstained"]

class HybridRetrievalRequestV1(TypedDict):
    """Complete hybrid retrieval request under deterministic RRF semantics v1."""
    lexical: LexicalRetrievalRequestV1
    lexical_weight: int
    limit: int
    vector: ExactRetrievalRequestV1
    vector_weight: int

class HybridRetrievalResponseV1(TypedDict):
    """Proof-bearing deterministic hybrid retrieval response."""
    outcome: HybridRetrievalOutcomeV1
    proof: RetrievalProofV1

class LexicalAbstentionV1(TypedDict):
    """Stable lexical abstention evidence."""
    query_tokens: list[str]
    reason: LexicalAbstentionReasonV1
    scanned_documents: int

class LexicalFieldContributionV1(TypedDict):
    """One configured-field contribution to a lexical term score."""
    field_length: int
    path: list[str]
    term_frequency: int

class LexicalFieldV1(TypedDict):
    """One configured field in an immutable lexical-index definition."""
    path: list[str]
    weight_micros: int

class LexicalIndexV1(TypedDict):
    """One immutable provider-free lexical-index definition."""
    fields: list[LexicalFieldV1]
    name: str

class LexicalRetrievalMatchV1(TypedDict):
    """One canonical lexical retrieval match."""
    key_hex: str
    score_nanos: int
    terms: list[LexicalTermContributionV1]

class LexicalRetrievalOutcomeV1Matches(TypedDict):
    """Accepted globally ranked matches."""
    matched_documents: int
    matches: list[LexicalRetrievalMatchV1]
    query_tokens: list[str]
    scanned_documents: int
    status: Literal["matches"]

class LexicalRetrievalOutcomeV1Abstained(TypedDict):
    """Typed normal abstention."""
    abstention: LexicalAbstentionV1
    status: Literal["abstained"]

class LexicalRetrievalRequestV1(TypedDict):
    """Durable provider-free lexical retrieval request under semantics v1."""
    lexical_index: str
    limit: int
    query: str
    timeout_ms: NotRequired[int | None]

class LexicalRetrievalResponseV1(TypedDict):
    """Proof-bearing durable lexical retrieval response."""
    outcome: LexicalRetrievalOutcomeV1
    proof: RetrievalProofV1

class LexicalTermContributionV1(TypedDict):
    """One canonical query-term contribution to a lexical result."""
    document_frequency: int
    fields: list[LexicalFieldContributionV1]
    score_nanos: int
    token: str

class MetricValueV1Count(TypedDict):
    """Unsigned count."""
    kind: Literal["count"]
    value: int

class MetricValueV1Integer(TypedDict):
    """Checked signed integer, represented as decimal to preserve `i128`."""
    kind: Literal["integer"]
    value: NotRequired[str | None]

class MetricValueV1Value(TypedDict):
    """Minimum or maximum structured value."""
    kind: Literal["value"]
    value: NotRequired[JsonValue]

class NamedMetricResultV1(TypedDict):
    """Named aggregate result."""
    name: str
    result: MetricValueV1

class NamedMetricV1Count(TypedDict):
    """Count every matched record."""
    metric: Literal["count"]
    name: str

class NamedMetricV1Sum(TypedDict):
    """Checked integer sum."""
    metric: Literal["sum"]
    name: str
    path: list[str]

class NamedMetricV1Min(TypedDict):
    """Minimum non-null value."""
    metric: Literal["min"]
    name: str
    path: list[str]

class NamedMetricV1Max(TypedDict):
    """Maximum non-null value."""
    metric: Literal["max"]
    name: str
    path: list[str]

class ProofV1(TypedDict):
    """Portable result proof plus its downloadable witness reference."""
    anchor_digest: str
    checkpoint_digest: NotRequired[str | None]
    checkpoint_sequence: int
    data: str
    encoding: str
    proof_digest: str
    snapshot_digest: str
    witness: WitnessV1

class PutRequestV1(TypedDict):
    """Atomic durable put batch."""
    records: list[RecordV1]
    transaction_id: NotRequired[str | None]

class PutVectorsRequestV1(TypedDict):
    """Atomic durable vector upsert batch."""
    transaction_id: NotRequired[str | None]
    vector_space: str
    vectors: list[VectorV1]

class QueryRequestV1(TypedDict):
    """Complete version 1 structured query request."""
    aggregation: NotRequired[AggregationPlanV1 | None]
    cursor: NotRequired[CursorV1 | None]
    filter: NotRequired[FilterV1]
    limit: int
    sort: NotRequired[list[SortFieldV1]]
    timeout_ms: NotRequired[int | None]

class QueryResponseV1(TypedDict):
    """Proof-bearing structured query response."""
    aggregation: NotRequired[AggregationResultV1 | None]
    matched_records: int
    next_cursor: NotRequired[CursorV1 | None]
    proof: ProofV1
    rows: list[RecordV1]
    scanned_records: int

class RecordV1(TypedDict):
    """One structured record on the wire."""
    key_hex: str
    value: JsonValue

class RetrievalProofV1(TypedDict):
    """Portable retrieval proof plus its downloadable witness reference."""
    anchor_digest: str
    checkpoint_digest: NotRequired[str | None]
    checkpoint_sequence: int
    data: str
    encoding: str
    proof_digest: str
    snapshot_digest: str
    witness: WitnessV1

class SortFieldV1(TypedDict):
    """One versioned sort field."""
    direction: SortDirectionV1
    nulls: NullPlacementV1
    path: list[str]

class VectorSpaceV1(TypedDict):
    """One immutable durable vector-space definition."""
    dimension: int
    metric: VectorMetricV1
    name: str

class VectorV1(TypedDict):
    """One canonical signed-Q15 vector on the wire."""
    key_hex: str
    values: list[int]

class WitnessV1(TypedDict):
    """Download reference for one canonical logical snapshot."""
    file_bytes: int
    path: str

CompareOperatorV1: TypeAlias = Literal["equal"] | Literal["not_equal"] | Literal["less"] | Literal["less_or_equal"] | Literal["greater"] | Literal["greater_or_equal"]
ExactAbstentionReasonV1: TypeAlias = Literal["no_candidates"] | Literal["below_threshold"] | Literal["ambiguous"]
ExactRetrievalOutcomeV1: TypeAlias = ExactRetrievalOutcomeV1Matches | ExactRetrievalOutcomeV1Abstained
FilterV1: TypeAlias = FilterV1MatchAll | FilterV1Exists | FilterV1Compare | FilterV1Prefix | FilterV1Contains | FilterV1All | FilterV1Any | FilterV1Not
GroupKeyValueV1: TypeAlias = GroupKeyValueV1Missing | GroupKeyValueV1Value
HybridBranchAbsenceV1: TypeAlias = Literal["lexical_no_candidates"] | Literal["vector_no_candidates"] | Literal["vector_below_threshold"] | Literal["vector_ambiguous"]
HybridRetrievalOutcomeV1: TypeAlias = HybridRetrievalOutcomeV1Matches | HybridRetrievalOutcomeV1Abstained
LexicalAbstentionReasonV1: TypeAlias = Literal["no_candidates"]
LexicalRetrievalOutcomeV1: TypeAlias = LexicalRetrievalOutcomeV1Matches | LexicalRetrievalOutcomeV1Abstained
MetricValueV1: TypeAlias = MetricValueV1Count | MetricValueV1Integer | MetricValueV1Value
NamedMetricV1: TypeAlias = NamedMetricV1Count | NamedMetricV1Sum | NamedMetricV1Min | NamedMetricV1Max
NullPlacementV1: TypeAlias = Literal["first"] | Literal["last"]
SortDirectionV1: TypeAlias = Literal["ascending"] | Literal["descending"]
VectorMetricV1: TypeAlias = Literal["cosine_q15_nanos"]

__all__ = [
    "AggregationPlanV1",
    "AggregationResultV1",
    "ApiLimitsV1",
    "CONTRACT_SHA256",
    "CapabilitiesV1",
    "CommitReceiptV1",
    "CompareOperatorV1",
    "CursorV1",
    "DefineLexicalIndexRequestV1",
    "DefineVectorSpaceRequestV1",
    "DeleteRequestV1",
    "DeleteVectorsRequestV1",
    "ErrorV1",
    "ExactAbstentionReasonV1",
    "ExactAbstentionV1",
    "ExactRetrievalMatchV1",
    "ExactRetrievalOutcomeV1",
    "ExactRetrievalOutcomeV1Abstained",
    "ExactRetrievalOutcomeV1Matches",
    "ExactRetrievalRequestV1",
    "ExactRetrievalResponseV1",
    "FilterV1",
    "FilterV1All",
    "FilterV1Any",
    "FilterV1Compare",
    "FilterV1Contains",
    "FilterV1Exists",
    "FilterV1MatchAll",
    "FilterV1Not",
    "FilterV1Prefix",
    "GetRequestV1",
    "GetResponseV1",
    "GroupKeyValueV1",
    "GroupKeyValueV1Missing",
    "GroupKeyValueV1Value",
    "GroupResultV1",
    "HealthV1",
    "HybridAbstentionV1",
    "HybridBranchAbsenceV1",
    "HybridExplanationV1",
    "HybridRetrievalMatchV1",
    "HybridRetrievalOutcomeV1",
    "HybridRetrievalOutcomeV1Abstained",
    "HybridRetrievalOutcomeV1Matches",
    "HybridRetrievalRequestV1",
    "HybridRetrievalResponseV1",
    "JsonValue",
    "LexicalAbstentionReasonV1",
    "LexicalAbstentionV1",
    "LexicalFieldContributionV1",
    "LexicalFieldV1",
    "LexicalIndexV1",
    "LexicalRetrievalMatchV1",
    "LexicalRetrievalOutcomeV1",
    "LexicalRetrievalOutcomeV1Abstained",
    "LexicalRetrievalOutcomeV1Matches",
    "LexicalRetrievalRequestV1",
    "LexicalRetrievalResponseV1",
    "LexicalTermContributionV1",
    "MetricValueV1",
    "MetricValueV1Count",
    "MetricValueV1Integer",
    "MetricValueV1Value",
    "NamedMetricResultV1",
    "NamedMetricV1",
    "NamedMetricV1Count",
    "NamedMetricV1Max",
    "NamedMetricV1Min",
    "NamedMetricV1Sum",
    "NullPlacementV1",
    "ProofV1",
    "PutRequestV1",
    "PutVectorsRequestV1",
    "QueryRequestV1",
    "QueryResponseV1",
    "RecordV1",
    "RetrievalProofV1",
    "SortDirectionV1",
    "SortFieldV1",
    "VectorMetricV1",
    "VectorSpaceV1",
    "VectorV1",
    "WitnessV1",
]
